from __future__ import annotations

from typing import Any

TEXTS: dict[str, dict[str, str]] = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "phone_prompt": "Telefon raqamingizni yuboring.",
        "phone_invalid": "Faqat o'zingizning raqamingizni yuboring.",
        "name_prompt": "Ism va familiyangizni kiriting (2-60 belgi).",
        "name_invalid": "Ism noto'g'ri. Faqat harf va bo'sh joydan foydalaning.",
        "age_prompt": "Yoshingizni kiriting (14-70).",
        "age_invalid": "Yosh noto'g'ri. 14 dan 70 gacha son kiriting.",
        "field_prompt": "Yo'nalishingizni tanlang:",
        "field_other_prompt": "Yo'nalishni kiriting (max 100 belgi).",
        "field_other_invalid": "Yo'nalish juda uzun yoki bo'sh.",
        "experience_prompt": "Tajriba darajangizni tanlang:",
        "purpose_prompt": "Maqsadingizni yozing (ixtiyoriy, max 200). Bekor qilish uchun '-' yuboring.",
        "purpose_invalid": "Matn juda uzun yoki link/spam mavjud.",
        "confirm_prompt": "Ma'lumotlaringiz:",
        "confirm_success": "Ro'yxatdan o'tish yakunlandi.",
        "restart_info": "Qayta to'ldirish boshlandi. Tilni tanlang:",
        "already_active": "Siz allaqachon ro'yxatdan o'tgansiz.",
        "need_reregister": "Siz qayta ro'yxatdan o'tishingiz kerak.",
        "not_registered_group": "Hurmatli {username}, iltimos avval ro'yxatdan o'ting.",
        "rejected_group": "Siz qayta ro'yxatdan o'tishingiz kerak.",
        "db_error": "Texnik nosozlik. Keyinroq urinib ko'ring.",
        "session_expired": "Sessiya tugadi. /start bosing.",
        "admin_reject_sent": "Ma'lumotlaringiz noto'g'ri. Qaytadan ro'yxatdan o'ting.",
        "admin_only": "Bu amal faqat adminlar uchun.",
        "reject_done": "Foydalanuvchi rejected holatga o'tkazildi.",
        "reject_not_found": "Foydalanuvchi topilmadi.",
        "reject_already": "Bu tugma allaqachon ishlatilgan.",
    },
    "ru": {
        "choose_language": "Выберите язык:",
        "phone_prompt": "Отправьте ваш номер телефона.",
        "phone_invalid": "Отправьте только свой номер.",
        "name_prompt": "Введите имя и фамилию (2-60 символов).",
        "name_invalid": "Некорректное имя. Только буквы и пробел.",
        "age_prompt": "Введите возраст (14-70).",
        "age_invalid": "Неверный возраст. Введите число 14-70.",
        "field_prompt": "Выберите направление:",
        "field_other_prompt": "Введите направление (до 100 символов).",
        "field_other_invalid": "Слишком длинное или пустое значение.",
        "experience_prompt": "Выберите опыт:",
        "purpose_prompt": "Напишите цель (необязательно, до 200). '-' для пропуска.",
        "purpose_invalid": "Слишком длинно или есть ссылка/спам.",
        "confirm_prompt": "Ваши данные:",
        "confirm_success": "Регистрация завершена.",
        "restart_info": "Заполняем заново. Выберите язык:",
        "already_active": "Вы уже зарегистрированы.",
        "need_reregister": "Нужно пройти регистрацию заново.",
        "not_registered_group": "Уважаемый {username}, сначала зарегистрируйтесь.",
        "rejected_group": "Вам нужно пройти регистрацию заново.",
        "db_error": "Техническая ошибка. Попробуйте позже.",
        "session_expired": "Сессия истекла. Нажмите /start.",
        "admin_reject_sent": "Ваши данные неверны. Пройдите регистрацию заново.",
        "admin_only": "Действие только для админов.",
        "reject_done": "Пользователь переведен в rejected.",
        "reject_not_found": "Пользователь не найден.",
        "reject_already": "Кнопка уже использована.",
    },
    "en": {
        "choose_language": "Choose language:",
        "phone_prompt": "Send your phone number.",
        "phone_invalid": "Please send your own phone number only.",
        "name_prompt": "Enter your full name (2-60 chars).",
        "name_invalid": "Invalid name. Use letters and spaces only.",
        "age_prompt": "Enter your age (14-70).",
        "age_invalid": "Invalid age. Enter a number from 14 to 70.",
        "field_prompt": "Choose your field:",
        "field_other_prompt": "Enter your field (max 100 chars).",
        "field_other_invalid": "Value is empty or too long.",
        "experience_prompt": "Choose experience level:",
        "purpose_prompt": "Write your purpose (optional, max 200). Send '-' to skip.",
        "purpose_invalid": "Text is too long or contains link/spam.",
        "confirm_prompt": "Your data:",
        "confirm_success": "Registration completed.",
        "restart_info": "Restarting form. Choose language:",
        "already_active": "You are already registered.",
        "need_reregister": "You need to register again.",
        "not_registered_group": "Dear {username}, please register first.",
        "rejected_group": "You need to register again.",
        "db_error": "Temporary technical issue. Please try again later.",
        "session_expired": "Session expired. Press /start.",
        "admin_reject_sent": "Your data is incorrect. Please register again.",
        "admin_only": "This action is allowed for admins only.",
        "reject_done": "User status updated to rejected.",
        "reject_not_found": "User not found.",
        "reject_already": "This button is already used.",
    },
}


def t(lang: str, key: str, **kwargs: Any) -> str:
    language = lang if lang in TEXTS else "uz"
    text = TEXTS[language].get(key, TEXTS["uz"].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
