from __future__ import annotations

TEXTS: dict[str, dict[str, str]] = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "group_required": "Botdan foydalanish uchun avval botni guruhingizga qoshing va admin huquqini bering.",
        "group_choose": "Qaysi guruh uchun royxatdan otmoqchisiz?",
        "group_not_found": "Guruh topilmadi. Botni guruhga qayta qoshib koring.",
        "phone_prompt": "Telefon raqamingizni yuboring.",
        "phone_invalid": "Faqat ozingizning raqamingizni yuboring.",
        "name_prompt": "Ism-familiyangizni kiriting (majburiy).",
        "name_invalid": "Ism-familiya majburiy. Faqat harf va bosh joy ishlating.",
        "age_prompt": "Yoshingizni kiriting (12-70).",
        "age_invalid": "Yosh notogri. 12 dan 70 gacha son kiriting.",
        "profession_prompt": "Kasbingizni yozing (max 100).",
        "profession_invalid": "Kasb bosh bolmasin va 100 belgidan oshmasin.",
        "experience_prompt": "Tajriba darajangizni tanlang:",
        "purpose_prompt": "Maqsadingizni yozing (ixtiyoriy, max 200). Otkazish uchun '-' yuboring.",
        "purpose_invalid": "Matn juda uzun yoki link/spam mavjud.",
        "confirm_prompt": "Malumotlaringiz:",
        "confirm_success": "Royxatdan otish yakunlandi.",
        "group_add_offer": "Endi botni oz guruhingizga qoshishingiz mumkin.",
        "other_name_prompt": "Ism-familiyangizni kiriting (majburiy).",
        "other_name_invalid": "Ism-familiya majburiy. Faqat harf va bosh joy ishlating.",
        "other_phone_prompt": "Telefon raqamingizni yuboring.",
        "other_phone_invalid": "Faqat ozingizning raqamingizni yuboring.",
        "other_age_prompt": "Yoshingizni kiriting (12-70).",
        "other_age_invalid": "Yosh notogri. 12 dan 70 gacha son kiriting.",
        "other_profession_prompt": "Kasbingizni yozing (max 100).",
        "other_profession_invalid": "Kasb bosh bolmasin va 100 belgidan oshmasin.",
        "other_experience_prompt": "Tajriba darajangizni tanlang:",
        "other_purpose_prompt": "Maqsadingizni yozing (ixtiyoriy, max 200). Otkazish uchun '-' yuboring.",
        "other_purpose_invalid": "Matn juda uzun yoki link/spam mavjud.",
        "other_confirm_prompt": "Malumotlaringiz:",
        "other_confirm_success": "Royxatdan otish yakunlandi.",
        "other_restart_info": "Qayta toldirish boshlandi. Tilni tanlang:",
        "other_group_add_offer": "Botni guruhingizga qoshishingiz mumkin.",
        "dm_register_intro": "{group_title} guruhida yozish uchun avval royxatdan oting.",
        "dch_dm_register_intro": "{username}, Dasturchilar Choyxonasi guruhida yozish uchun avval royxatdan oting.",
        "other_dm_register_intro": "{username}, {group_title} guruhida yozish uchun avval royxatdan oting.",
        "restart_info": "Qayta toldirish boshlandi. Tilni tanlang:",
        "already_active": "Siz allaqachon royxatdan otgansiz.",
        "need_reregister": "Siz qayta royxatdan otishingiz kerak.",
        "not_registered_group": "Hurmatli {username}, iltimos avval royxatdan oting.",
        "rejected_group": "{username}, siz qayta royxatdan otishingiz kerak.",
        "db_error": "Texnik nosozlik. Keyinroq urinib koring.",
        "session_expired": "Sessiya tugadi. /start bosing.",
        "admin_reject_sent": "Malumotlaringiz notogri. Iltimos, qaytadan toldiring va aniqlik kiriting.",
        "admin_only": "Bu amal faqat adminlar uchun.",
        "reject_done": "Foydalanuvchi rejected holatga otkazildi.",
        "reject_not_found": "Foydalanuvchi topilmadi.",
        "reject_already": "Bu tugma allaqachon ishlatilgan.",
    },
    "ru": {
        "choose_language": "Выберите язык:",
        "group_required": "Чтобы использовать бота, добавьте его в свою группу и выдайте права администратора.",
        "group_choose": "Для какой группы пройти регистрацию?",
        "group_not_found": "Группа не найдена. Добавьте бота заново.",
        "phone_prompt": "Отправьте ваш номер телефона.",
        "phone_invalid": "Отправьте только свой номер.",
        "name_prompt": "Введите имя и фамилию (обязательно).",
        "name_invalid": "Имя и фамилия обязательны. Используйте только буквы и пробелы.",
        "age_prompt": "Введите возраст (12-70).",
        "age_invalid": "Неверный возраст. Введите число от 12 до 70.",
        "profession_prompt": "Напишите профессию (макс. 100 символов).",
        "profession_invalid": "Поле пустое или слишком длинное (макс. 100 символов).",
        "experience_prompt": "Выберите опыт:",
        "purpose_prompt": "Напишите цель (необязательно, до 200 символов). Отправьте '-' для пропуска.",
        "purpose_invalid": "Текст слишком длинный или содержит ссылку/спам.",
        "confirm_prompt": "Ваши данные:",
        "confirm_success": "Регистрация завершена.",
        "group_add_offer": "Теперь можно добавить бота в свою группу.",
        "other_name_prompt": "Введите имя и фамилию (обязательно).",
        "other_name_invalid": "Имя и фамилия обязательны. Используйте только буквы и пробелы.",
        "other_phone_prompt": "Отправьте ваш номер телефона.",
        "other_phone_invalid": "Отправьте только свой номер.",
        "other_age_prompt": "Введите возраст (12-70).",
        "other_age_invalid": "Неверный возраст. Введите число от 12 до 70.",
        "other_profession_prompt": "Напишите профессию (макс. 100 символов).",
        "other_profession_invalid": "Поле пустое или слишком длинное (макс. 100 символов).",
        "other_experience_prompt": "Выберите опыт:",
        "other_purpose_prompt": "Напишите цель (необязательно, до 200 символов). Отправьте '-' для пропуска.",
        "other_purpose_invalid": "Текст слишком длинный или содержит ссылку/спам.",
        "other_confirm_prompt": "Ваши данные:",
        "other_confirm_success": "Регистрация завершена.",
        "other_restart_info": "Заполняем заново. Выберите язык:",
        "other_group_add_offer": "Теперь можно добавить бота в свою группу.",
        "dm_register_intro": "Чтобы писать в группе {group_title}, сначала пройдите регистрацию в боте.",
        "dch_dm_register_intro": "{username}, чтобы писать в группе Dasturchilar Choyxonasi, сначала пройдите регистрацию в боте.",
        "other_dm_register_intro": "{username}, чтобы писать в группе {group_title}, сначала пройдите регистрацию в боте.",
        "restart_info": "Заполняем заново. Выберите язык:",
        "already_active": "Вы уже зарегистрированы.",
        "need_reregister": "Нужно пройти регистрацию заново.",
        "not_registered_group": "Уважаемый {username}, сначала зарегистрируйтесь.",
        "rejected_group": "{username}, вам нужно пройти регистрацию заново.",
        "db_error": "Техническая ошибка. Попробуйте позже.",
        "session_expired": "Сессия истекла. Нажмите /start.",
        "admin_reject_sent": "Мы проверили данные. Пожалуйста, заполните форму заново и уточните информацию.",
        "admin_only": "Действие доступно только администраторам.",
        "reject_done": "Пользователь переведён в статус rejected.",
        "reject_not_found": "Пользователь не найден.",
        "reject_already": "Кнопка уже использована.",
    },
    "en": {
        "choose_language": "Choose language:",
        "group_required": "To use this bot, add it to your group and grant admin rights.",
        "group_choose": "Choose the group for registration:",
        "group_not_found": "Group not found. Please add the bot again.",
        "phone_prompt": "Send your phone number.",
        "phone_invalid": "Please send your own phone number only.",
        "name_prompt": "Enter your full name (required).",
        "name_invalid": "Full name is required. Use letters and spaces only.",
        "age_prompt": "Enter your age (12-70).",
        "age_invalid": "Invalid age. Enter a number from 12 to 70.",
        "profession_prompt": "Enter your profession (max 100 chars).",
        "profession_invalid": "Profession is empty or too long (max 100).",
        "experience_prompt": "Choose experience level:",
        "purpose_prompt": "Write your purpose (optional, max 200). Send '-' to skip.",
        "purpose_invalid": "Text is too long or contains link/spam.",
        "confirm_prompt": "Your data:",
        "confirm_success": "Registration completed.",
        "group_add_offer": "Now you can add this bot to your own group.",
        "other_name_prompt": "Enter your full name (required).",
        "other_name_invalid": "Full name is required. Use letters and spaces only.",
        "other_phone_prompt": "Send your phone number.",
        "other_phone_invalid": "Please send your own phone number only.",
        "other_age_prompt": "Enter your age (12-70).",
        "other_age_invalid": "Invalid age. Enter a number from 12 to 70.",
        "other_profession_prompt": "Enter your profession (max 100 chars).",
        "other_profession_invalid": "Profession is empty or too long (max 100).",
        "other_experience_prompt": "Choose experience level:",
        "other_purpose_prompt": "Write your purpose (optional, max 200). Send '-' to skip.",
        "other_purpose_invalid": "Text is too long or contains link/spam.",
        "other_confirm_prompt": "Your data:",
        "other_confirm_success": "Registration completed.",
        "other_restart_info": "Restarting form. Choose language:",
        "other_group_add_offer": "Now you can add this bot to your own group.",
        "dm_register_intro": "To write in group {group_title}, please register in the bot first.",
        "dch_dm_register_intro": "{username}, to write in Dasturchilar Choyxonasi group, please register in the bot first.",
        "other_dm_register_intro": "{username}, to write in group {group_title}, please register in the bot first.",
        "restart_info": "Restarting form. Choose language:",
        "already_active": "You are already registered.",
        "need_reregister": "You need to register again.",
        "not_registered_group": "Dear {username}, please register first.",
        "rejected_group": "{username}, you need to register again.",
        "db_error": "Temporary technical issue. Please try again later.",
        "session_expired": "Session expired. Press /start.",
        "admin_reject_sent": "We reviewed your data. Please fill the form again with correct details.",
        "admin_only": "This action is allowed for admins only.",
        "reject_done": "User status updated to rejected.",
        "reject_not_found": "User not found.",
        "reject_already": "This button is already used.",
    },
}
