from __future__ import annotations

TEXTS: dict[str, dict[str, str]] = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "group_required": "Botdan foydalanish uchun avval botni guruhingizga qoshing va admin huquqini bering.",
        "group_choose": "Qaysi guruh uchun royxatdan otmoqchisiz?",
        "group_not_found": "Guruh topilmadi. Botni guruhga qayta qoshib koring.",
        "phone_prompt": "Telefon raqamingizni yuboring.",
        "phone_invalid": "Faqat ozingizning raqamingizni yuboring.",
        "name_prompt": "Ism familiyangizni kiriting (ixtiyoriy). Otkazib yuborish uchun '-' yuboring.",
        "name_invalid": "Ism notogri. Faqat harf va bosh joy ishlating yoki '-' yuboring.",
        "age_prompt": "Yoshingizni kiriting (12-70).",
        "age_invalid": "Yosh notogri. 12 dan 70 gacha son kiriting.",
        "profession_prompt": "Kasbingizni yozing (max 100).",
        "profession_invalid": "Kasb bosh bolmasin va 100 belgidan oshmasin.",
        "experience_prompt": "Tajriba darajangizni tanlang:",
        "purpose_prompt": "Maqsadingizni yozing (ixtiyoriy, max 200). Otkazish uchun '-' yuboring.",
        "purpose_invalid": "Matn juda uzun yoki link/spam mavjud.",
        "confirm_prompt": "Malumotlaringiz:",
        "confirm_success": "Royxatdan otish yakunlandi.",
        "group_add_offer": "Endi botni oz guruhingizga qoshishingiz mumkin.",
        "other_name_prompt": "Ism-familiyangizni kiriting (ixtiyoriy). Otkazib yuborish uchun '-' yuboring.",
        "other_name_invalid": "Ism notogri. Faqat harf va bosh joy ishlating yoki '-' yuboring.",
        "other_phone_prompt": "Telefon raqamingizni yuboring.",
        "other_phone_invalid": "Faqat ozingizning raqamingizni yuboring.",
        "other_age_prompt": "Yoshingizni kiriting (12-70).",
        "other_age_invalid": "Yosh notogri. 12 dan 70 gacha son kiriting.",
        "other_profession_prompt": "Kasbingizni yozing (max 100).",
        "other_profession_invalid": "Kasb bosh bolmasin va 100 belgidan oshmasin.",
        "other_experience_prompt": "Tajriba darajangizni tanlang:",
        "other_purpose_prompt": "Maqsadingizni yozing (ixtiyoriy, max 200). Otkazish uchun '-' yuboring.",
        "other_purpose_invalid": "Matn juda uzun yoki link/spam mavjud.",
        "other_confirm_prompt": "Malumotlaringiz:",
        "other_confirm_success": "Royxatdan otish yakunlandi.",
        "other_restart_info": "Qayta toldirish boshlandi. Tilni tanlang:",
        "other_group_add_offer": "Botni guruhingizga qoshishingiz mumkin.",
        "dm_register_intro": "{group_title} guruhida yozish uchun avval royxatdan oting.",
        "dch_dm_register_intro": "{username}, Dasturchilar Choyxonasi guruhida yozish uchun avval royxatdan oting.",
        "other_dm_register_intro": "{username}, {group_title} guruhida yozish uchun avval royxatdan oting.",
        "restart_info": "Qayta toldirish boshlandi. Tilni tanlang:",
        "already_active": "Siz allaqachon royxatdan otgansiz.",
        "need_reregister": "Siz qayta royxatdan otishingiz kerak.",
        "not_registered_group": "Hurmatli {username}, iltimos avval royxatdan oting.",
        "rejected_group": "Siz qayta royxatdan otishingiz kerak.",
        "db_error": "Texnik nosozlik. Keyinroq urinib koring.",
        "session_expired": "Sessiya tugadi. /start bosing.",
        "admin_reject_sent": "Malumotlaringiz notogri. Iltimos, qaytadan toldiring va aniqlik kiriting.",
        "admin_only": "Bu amal faqat adminlar uchun.",
        "reject_done": "Foydalanuvchi rejected holatga otkazildi.",
        "reject_not_found": "Foydalanuvchi topilmadi.",
        "reject_already": "Bu tugma allaqachon ishlatilgan.",
    },
    "ru": {
        "choose_language": "Vyberite yazyk:",
        "group_required": "Chtoby ispolzovat bota, dobavte ego v svoyu gruppu i vydajte admin prava.",
        "group_choose": "Dlya kakoy gruppy proyti registratsiyu?",
        "group_not_found": "Gruppa ne naydena. Dobavte bota zanovo.",
        "phone_prompt": "Otpravte vash nomer telefona.",
        "phone_invalid": "Otpravte tolko svoy nomer.",
        "name_prompt": "Vvedite imya i familiyu (neobyazatelno). Dlya propuska otpravte '-'.",
        "name_invalid": "Nekorrektnoe imya. Tolko bukvy/probel ili '-'.",
        "age_prompt": "Vvedite vozrast (12-70).",
        "age_invalid": "Nevernyy vozrast. Vvedite chislo 12-70.",
        "profession_prompt": "Napishite professiyu (max 100).",
        "profession_invalid": "Pole pustoe ili slishkom dlinnoe (max 100).",
        "experience_prompt": "Vyberite opyt:",
        "purpose_prompt": "Napishite tsel (neobyazatelno, do 200). '-' dlya propuska.",
        "purpose_invalid": "Slishkom dlinno ili est ssylka/spam.",
        "confirm_prompt": "Vashi dannye:",
        "confirm_success": "Registratsiya zavershena.",
        "group_add_offer": "Teper mozhno dobavit bota v svoyu gruppu.",
        "other_name_prompt": "Vvedite imya i familiyu (neobyazatelno). Dlya propuska otpravte '-'.",
        "other_name_invalid": "Nekorrektnoe imya. Tolko bukvy/probel ili '-'.",
        "other_phone_prompt": "Otpravte vash nomer telefona.",
        "other_phone_invalid": "Otpravte tolko svoy nomer.",
        "other_age_prompt": "Vvedite vozrast (12-70).",
        "other_age_invalid": "Nevernyy vozrast. Vvedite chislo 12-70.",
        "other_profession_prompt": "Napishite professiyu (max 100).",
        "other_profession_invalid": "Pole pustoe ili slishkom dlinnoe (max 100).",
        "other_experience_prompt": "Vyberite opyt:",
        "other_purpose_prompt": "Napishite tsel (neobyazatelno, do 200). '-' dlya propuska.",
        "other_purpose_invalid": "Slishkom dlinno ili est ssylka/spam.",
        "other_confirm_prompt": "Vashi dannye:",
        "other_confirm_success": "Registratsiya zavershena.",
        "other_restart_info": "Zapolnyaem zanovo. Vyberite yazyk:",
        "other_group_add_offer": "Teper mozhno dobavit bota v svoyu gruppu.",
        "dm_register_intro": "Chtoby pisat v gruppe {group_title}, snachala proydite registratsiyu v bote.",
        "dch_dm_register_intro": "{username}, chtoby pisat v gruppe Dasturchilar Choyxonasi, snachala proydite registratsiyu v bote.",
        "other_dm_register_intro": "{username}, chtoby pisat v gruppe {group_title}, snachala proydite registratsiyu v bote.",
        "restart_info": "Zapolnyaem zanovo. Vyberite yazyk:",
        "already_active": "Vy uzhe zaregistrirovany.",
        "need_reregister": "Nuzhno proyti registratsiyu zanovo.",
        "not_registered_group": "Uvazhaemyy {username}, snachala zaregistriruytes.",
        "rejected_group": "Vam nuzhno proyti registratsiyu zanovo.",
        "db_error": "Tekhnicheskaya oshibka. Poprobuyte pozzhe.",
        "session_expired": "Sessiya istekla. Nazhmite /start.",
        "admin_reject_sent": "My proverili dannye. Pozhaluysta, zapolnite povtorno i utochnite.",
        "admin_only": "Deystvie tolko dlya adminov.",
        "reject_done": "Polzovatel pereveden v rejected.",
        "reject_not_found": "Polzovatel ne nayden.",
        "reject_already": "Knopka uzhe ispolzovana.",
    },
    "en": {
        "choose_language": "Choose language:",
        "group_required": "To use this bot, add it to your group and grant admin rights.",
        "group_choose": "Choose the group for registration:",
        "group_not_found": "Group not found. Please add the bot again.",
        "phone_prompt": "Send your phone number.",
        "phone_invalid": "Please send your own phone number only.",
        "name_prompt": "Enter your full name (optional). Send '-' to skip.",
        "name_invalid": "Invalid name. Use letters/spaces only, or send '-'.",
        "age_prompt": "Enter your age (12-70).",
        "age_invalid": "Invalid age. Enter a number from 12 to 70.",
        "profession_prompt": "Enter your profession (max 100 chars).",
        "profession_invalid": "Profession is empty or too long (max 100).",
        "experience_prompt": "Choose experience level:",
        "purpose_prompt": "Write your purpose (optional, max 200). Send '-' to skip.",
        "purpose_invalid": "Text is too long or contains link/spam.",
        "confirm_prompt": "Your data:",
        "confirm_success": "Registration completed.",
        "group_add_offer": "Now you can add this bot to your own group.",
        "other_name_prompt": "Enter your full name (optional). Send '-' to skip.",
        "other_name_invalid": "Invalid name. Use letters/spaces only, or send '-'.",
        "other_phone_prompt": "Send your phone number.",
        "other_phone_invalid": "Please send your own phone number only.",
        "other_age_prompt": "Enter your age (12-70).",
        "other_age_invalid": "Invalid age. Enter a number from 12 to 70.",
        "other_profession_prompt": "Enter your profession (max 100 chars).",
        "other_profession_invalid": "Profession is empty or too long (max 100).",
        "other_experience_prompt": "Choose experience level:",
        "other_purpose_prompt": "Write your purpose (optional, max 200). Send '-' to skip.",
        "other_purpose_invalid": "Text is too long or contains link/spam.",
        "other_confirm_prompt": "Your data:",
        "other_confirm_success": "Registration completed.",
        "other_restart_info": "Restarting form. Choose language:",
        "other_group_add_offer": "Now you can add this bot to your own group.",
        "dm_register_intro": "To write in group {group_title}, please register in the bot first.",
        "dch_dm_register_intro": "{username}, to write in Dasturchilar Choyxonasi group, please register in the bot first.",
        "other_dm_register_intro": "{username}, to write in group {group_title}, please register in the bot first.",
        "restart_info": "Restarting form. Choose language:",
        "already_active": "You are already registered.",
        "need_reregister": "You need to register again.",
        "not_registered_group": "Dear {username}, please register first.",
        "rejected_group": "You need to register again.",
        "db_error": "Temporary technical issue. Please try again later.",
        "session_expired": "Session expired. Press /start.",
        "admin_reject_sent": "We reviewed your data. Please fill the form again with correct details.",
        "admin_only": "This action is allowed for admins only.",
        "reject_done": "User status updated to rejected.",
        "reject_not_found": "User not found.",
        "reject_already": "This button is already used.",
    },
}
